stages:
  - .pre
  - test
  - build
  - deploy

variables:
  PKG_PREFIX: luucy-embed
  WEB_PREFIX: sample-next-app
  PLUGIN_PREFIX: sample-luucy-plugin

default:
  image: node:latest
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

embed:setup:
  stage: .pre
  script:
    - cd $CI_PROJECT_DIR/$PKG_PREFIX && npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - $PKG_PREFIX/node_modules

embed:lint:
  stage: test
  dependencies:
    - embed:setup
  needs:
    - embed:setup
  script:
    - cd $CI_PROJECT_DIR/$PKG_PREFIX && npm run lint

embed:test:
  stage: test
  dependencies:
    - embed:setup
  needs:
    - embed:setup
  script:
    - cd $CI_PROJECT_DIR/$PKG_PREFIX && npm run coverage
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $PKG_PREFIX/coverage/cobertura-coverage.xml
      junit: $PKG_PREFIX/junit.xml

embed:build:
  stage: build
  dependencies:
    - embed:setup
  needs:
    - embed:setup
    - embed:lint
    - embed:test
  script:
    - cd $CI_PROJECT_DIR/$PKG_PREFIX && mkdir -p .npm
    - cd $CI_PROJECT_DIR/$PKG_PREFIX && npm run build
  artifacts:
    paths:
      - .npm

web:setup:
  stage: .pre
  script:
    - 'echo "Using Web directory: $WEB_PREFIX"'
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - $WEB_PREFIX/node_modules

web:lint:
  stage: test
  dependencies:
    - web:setup
  needs:
    - web:setup
  script:
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && npm run lint

web:build:
  stage: build
  dependencies:
    - web:setup
  needs:
    - web:setup
    - web:lint
  variables:
    NEXT_PUBLIC_PUBLIC_URL: $CI_PAGES_URL
  script:
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && npm run build
  artifacts:
    paths:
      - $WEB_PREFIX/out

pages:mr:
  stage: deploy
  dependencies:
    - web:build
  needs:
    - web:build
  script:
    - echo 'Dry run for pages deployment'
    - cd $CI_PROJECT_DIR && rm -rf public
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && mkdir -p ../public && mv out/* ../public
    - cd $CI_PROJECT_DIR && mkdir -p public/sample-html-app && mv sample-html-app/* public/sample-html-app
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  dependencies:
    - web:build
  needs:
    - web:build
  script:
    - cd $CI_PROJECT_DIR && rm -rf public
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && mkdir -p ../public && mv out/* ../public
    - cd $CI_PROJECT_DIR && mkdir -p public/sample-html-app && mv sample-html-app/* public/sample-html-app
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: prod
    url: $CI_PAGES_URL

plugin:setup:
  stage: .pre
  script:
    - 'echo "Using Plugn directory: $PLUGIN_PREFIX"'
    - cd $CI_PROJECT_DIR/$PLUGIN_PREFIX && npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - $PLUGIN_PREFIX/node_modules

plugin:lint:
  stage: test
  dependencies:
    - plugin:setup
  needs:
    - plugin:setup
  script:
    - cd $CI_PROJECT_DIR/$PLUGIN_PREFIX && npm run lint

plugin:build:
  stage: build
  dependencies:
    - plugin:setup
  needs:
    - plugin:setup
    - plugin:lint
  script:
    - cd $CI_PROJECT_DIR/$PLUGIN_PREFIX && npm run build
  artifacts:
    paths:
      - $PLUGIN_PREFIX/bundles
