stages:
  - .pre
  - test
  - build
  - deploy

variables:
  PKG_PREFIX: luucy-embed
  WEB_PREFIX: sample-next-app
  PLUGIN_PREFIX: sample-luucy-plugin

default:
  image: node:latest
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/

setup:
  stage: .pre
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules
      - "**/node_modules"

lint:
  stage: test
  dependencies:
    - setup
  needs:
    - setup
  script:
    - npm run lint --workspaces --if-present

test:
  stage: test
  dependencies:
    - setup
  needs:
    - setup
  script:
    - npm run coverage --workspaces --if-present
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: $PKG_PREFIX/coverage/cobertura-coverage.xml
      junit: $PKG_PREFIX/junit.xml

build:
  stage: build
  dependencies:
    - setup
  needs:
    - setup
    - lint
    - test
  script:
    - npm run build --workspaces --if-present
  artifacts:
    paths:
      - $PKG_PREFIX/dist
      - $WEB_PREFIX/out
      - $PLUGIN_PREFIX/bundles

embed:deploy-mr:
  stage: deploy
  dependencies:
    - build
  needs:
    - build
  script:
    - npm publish --dry-run -w $PKG_PREFIX
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:mr:
  stage: deploy
  dependencies:
    - build
  needs:
    - build
  script:
    - echo 'Dry run for pages deployment'
    - cd $CI_PROJECT_DIR && rm -rf public
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && mkdir -p ../public && mv out/* ../public
    - cd $CI_PROJECT_DIR && mkdir -p public/sample-html-app && mv sample-html-app/* public/sample-html-app
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  dependencies:
    - build
  needs:
    - build
  script:
    - cd $CI_PROJECT_DIR && rm -rf public
    - cd $CI_PROJECT_DIR/$WEB_PREFIX && mkdir -p ../public && mv out/* ../public
    - cd $CI_PROJECT_DIR && mkdir -p public/sample-html-app && mv sample-html-app/* public/sample-html-app
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: prod
    url: $CI_PAGES_URL
