// enabled declarations, generated by luucy cli
// autogenerated. changes will be overwritten

/// <reference no-default-lib="true"/>
/// <reference path="../node_modules/luucy-types/globals/index.d.ts" />

/// <reference path="../node_modules/luucy-types/scopes/core/index.d.ts" />
/// <reference path="../node_modules/luucy-types/scopes/data/index.d.ts" />
/// <reference path="../node_modules/luucy-types/scopes/embed/index.d.ts" />
/// <reference path="../node_modules/luucy-types/scopes/map/index.d.ts" />
/// <reference path="../node_modules/luucy-types/scopes/map.location/index.d.ts" />
/// <reference path="../node_modules/luucy-types/scopes/ui/index.d.ts" />
